platform :ios, '8.0'

target 'example' do
  # use_frameworks!

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    "Core",
    "BatchedBridge",
    "DevSupport",
    "ART",
    'RCTAnimation',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  target 'exampleTests' do
    inherit! :search_paths
  end
end
