platform :ios, '8.0'

target 'RNAdtech' do
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTVibration',
    'RCTSettings',
    'RCTPushNotification',
    'RCTActionSheet',
    'DevSupport'
  ]

  pod 'AdTechMobileSdk', :path => '../libraries/ios'
end